### ISSUE TITLE
Roadmap towards 2.0 - Requests for Comments

### ISSUE THREAD

**Issue by estilles** [howardabrams/node-mocks-http#54]
## Roadmap  to node-mocks-http v2.0

We want `node-mocks-http` to provide Express `4.x` compatible `request` and `response` object mocks. As with `1.x` we want `2.x` to be as lightweight and dependency free as possible.

The list below is a first draft of our roadmap towards `2.0`. It is by no means comprehensive or final. Comments, questions and requests are most definitely welcome.
### Proposed Changes
- [x] <del>add `mockStream` (with sufficient functionality for `mockStreamReadable`), which will inherit from `EventEmitter`</del> used real `Stream`
- [x] deprecate `mockEventEmitter` in favor using a real `EventEmitter`
- [x] <del>add `mockStreamReadable` (with sufficient functionality for `mockHttpIncomingMessage`), which will inherit from `mockStream`</del> used real `Stream.Readable`
- [x] <del>update `mockStreamWritable` (with sufficient functionality for `mockHttpOutgoingMessage`), which will inherit from `mockStream`</del>  used real `Stream.Writable`
- [x] add <del>`mockHttpIncomingMessage`</del> `node/_http_incoming.js` (to mock `http.IncomingMessage`), which will inherit from `mockStreamReadable`
- [ ] add `mockHttpOutgoingMessage` (to mock `http.OutgoingMessage`), which will inherit from `mockWritableReadable`
- [ ] add `mockHttpServerResponse` (to mock `http.ServerResponse`)
- [ ] add `mockApp`, which will serve as a parent to `mockRequest` and `mockResponse`, and will perform some initialization task, so as associating `mockRequest` with `mockResponse` (and vice versa). It will likewise provide the ability to configure Express-related settings that have an effect on `request` and `response`
- [ ] deprecate `.createRequest()` and `.createResponse()` methods in favor of a `.createApp()`, which will return an `mockApp` instance that includes both a `mockRequest` and a `mockResponse` instance.

> NOTE: The intent of the above mocks is to support (via inheritance) `mockRequest` and `mockResponse`. These will contain only a subset of their "real life" counterparts. They will be used internally by `node-mocks-http` and will not be exported for consumption.
> 
> We will consider expanding them to full-blown mocks that can be made available for public consumption in future versions of `node-mocks-http`.
- [x] update `mockRequest` to inherit from `mockHttpIncomingMessage`
- [ ] update `mockResponse` to inherit form `mockHttpServerResponse`
- [ ] add  warning for all deprecated Express functionality (maybe using ~~deprecate~~ [depd](https://www.npmjs.com/package/depd) as Express does)
### Pending Issues

The proposed changes for `2.0` will either response or provide a means to resolve all pending issues.
- [ ] - #12 - add .headersSent to mockResponse
- [ ] - #17 - requests should be event emitters
- [ ] - #45 - associate a req with res and vice versa
- [ ] - #49 - mockResponse.send() does not call .end()
### Comments and Contributions

If you're a `node-mocks-http` user/consumer we would love to hear your thoughts regarding our **2.0 Roadmap**. Please leave your comments below.

For those of you who wish to contribute, <del>we will be creating `2.x` branch during the first week of April against which you can submit your pull requests.</del> we've merged our progress of `2.x` onto `master`. Submit any pull request for `2.x` against `master`. Please read and follow our [contributing guidelines](https://github.com/howardabrams/node-mocks-http/blob/master/CONTRIBUTING.md) prior to your submission.
